### ISSUE TITLE
I need help with some information in the view.gtkw file

### ISSUE THREAD

**Issue by ger534** [GreenWaves-Technologies/gap_sdk#154]
Hi, right now I'm working in a library to analyze a pausable improvement on execution time.

I wanted to use the GVSOC platform to do the benchmarking in some error-tolerant applications.

The plan was simple: 
- run the application in GVSOC, measure execution time or clock cycles
- now run it again in GVSOC but implementing the new library and again, measure execution time or clock cycles

I saw this video https://greenwaves-technologies.com/gvsoc-the-full-system-simulator-for-profiling-gap-applications/  and assumed that the best way to measure execution time or clock cycles was using the runner argument "--vcd" how is suggested in the video.

I have the images of my application in GTKwave, like this one:
![gtkwave_inversek2j](https://user-images.githubusercontent.com/15766506/87699606-570df680-c752-11ea-9eca-ac1ffc4af991.jpg)

I thought that I could use the time marker at the end of the time axis as execution time but I'm not really sure if that's the execution time or not, I don't know to measure the execution time with the signals provided in this .vcd file. Something else about the signals that you can see in the simulation is the signals "period", "udma" and "fc". To be honest, I don't know what represents each label. There's any documentation for this besides the video? Because I already read all the GVSOC documentation (https://gvsoc.readthedocs.io/en/latest/vcd_traces.html) and also the GTKwave documentation (http://gtkwave.sourceforge.net/gtkwave.pdf) but everything is fine in the configuration of the tools. My problem right now is the lack of knowledge on how to measure execution time or clock cycles. I don't have a problem if the measurement needs to be in code or the waves, but I want to use GAP metrics because that's way cooler.

I would appreciate guidance in the measurement subject.

**Comment by Yaooooo** [comment]
Hi

Truely sorry for late reply. 
I will firstly explain your question about "cycle" and "time":

- 1 cycle means the internal clock cycled 1 time
- How to convert it to time depends on which frequency your chip is working with.

So for example, if your chip works with 100MHz, which means, the chip clock 100M cycles in 1 secs. In this case, if your execution time is 12345678 cycles, it means the execution time is: 12345678/100000000 secs.

Since GAP8 can change it frequency dynamically, you need to do this calculation to have the execution time. 

Secondly, about measuring the performance in GAP8:

- Of cause you can measure this by using gvsoc and gtkwave, by getting the cycle number and devide them by actual frequency of GAP8.

- You can also get them by using our performance counter, here's some api and example for that: 

    - api: https://greenwaves-technologies.com/manuals/BUILD/PMSIS_API/html/group__GAP8__PERF.html
    - example: https://github.com/GreenWaves-Technologies/gap_sdk/tree/master/examples/pmsis/periph/perf

FYI, GVSOC is a virtual platform for GAP, it can SIMULATE how GAP chip works. This means the performance you got from GVSOC won't be 100% the same on a real chip. 

-
