### ISSUE TITLE
PulpOS threads_events hangs

### ISSUE THREAD

**Issue by dvcirilo** [GreenWaves-Technologies/gap_sdk#167]
Hello,

I've been trying to run the threads_events example on v3.1 and now on v3.7.1 and none of them works, not even on gvsoc.

Other examples are working.

Am I missing something?

**Comment by Yaooooo** [comment]
Hi, 

Could you please tell me what you are looking for?
This is an old example in pure pulp-os, to use the scheduler and event (but not thread, since the pulp-os is an event driven system, it doesn't support multi-thread).
Today, we don't have pure scheduler example in the sdk, however, you can take a look into all the example pmsis which is using "pi_yield()", for example:
example/pmsis/bsp/flash/hyper_flash/test_hyper_flash.c

If this doesn't meet your need, please let me know.

**Comment by dvcirilo** [comment]
I am looking for exactly that, using time-sharing threads. I was expecting that the included examples would work.

I'll take a look at the PMSIS examples. Would you recommend it for new projects over pulp-os?

Thank you!

**Comment by Yaooooo** [comment]
Sorry for late reply. In fact PMSIS is not at all conflict with pulp-os.
PMSIS is an api level which can be easily plugged into any RTOS like this:
![image](https://user-images.githubusercontent.com/4712667/97117511-885c7200-1704-11eb-9683-1c4b7981f343.png)

In this case, we can benefit in using the same API with different RTOS. 
Sorry for our poor documentation, we are trying to improve that.
