### ISSUE TITLE
can use gdb to debug cluster core(x)?

### ISSUE THREAD

**Issue by MrHaiCoder** [GreenWaves-Technologies/gap_sdk#235]

**Comment by Yaooooo** [comment]
Sorry, due to some hardware limitation, we cannot support gdb on GAP8.
You can try to use our virtual platform GVSOC to debug the cluster part, here's a blog on how to use it: https://greenwaves-technologies.com/gvsoc-the-full-system-simulator-for-profiling-gap-applications/

Please let us know if you have further question on this.

**Comment by Yaooooo** [comment]
No feedback, close issue.
