### ISSUE TITLE
FaceDetecion error

### ISSUE THREAD

**Issue by HaolinChen** [GreenWaves-Technologies/gap_sdk#238]
Hi, I'm using AI-DECK now .When I run CannyEdgeDetection and MultiScalePedestrianDetector there is no problem.
But when I run FaceDetection the error occur.
![face_error1](https://user-images.githubusercontent.com/68801428/121765513-e186f200-cb7d-11eb-8d59-f3cd17977ba9.png)
I'm using the latest version of gap_SDK 4.0.0 and I'm sure all the tools have been installed correctly.

**Comment by Yaooooo** [comment]
Hi, 

Seems you are using our example in our gap_sdk, but not the one in AI_DECK repo: https://github.com/bitcraze/AIdeck_examples
Since we are not the maintainer of AIDeck repo, we won't support natively the AI Deck BSP in our SDK.

You can try the examples prepared by bitcraze in the repo above. Otherwise, you can easily using our BSP lib, drivers, api write an AI Deck BSP. In this case, you can easily use all the examples in our SDK.

Here's an example on how to write a customer BSP : https://github.com/GreenWaves-Technologies/gap_sdk/tree/master/examples/customer_bsp

Yao
