### ISSUE TITLE
Issue with gvsoc

### ISSUE THREAD

**Issue by HaolinChen** [GreenWaves-Technologies/gap_sdk#244]
I can't run any demos with gvsoc. Error occurs like this.
`[/sys/board/chip/soc/efuse/warning] Unable to load stimuli file: efuse_preload.data: No such file or directory`
I've tried to update my gap sdk and rebuild all tools, including gvsoc, it seems no problem occurs when making gvsoc, but still the same error occurs when I try to run helloworld on gosvc.

**Comment by Yaooooo** [comment]
Hi,

Can you please be precise on:

- which version of SDK (which commit) you are using?
- how you configure your env ?
- how you build the sdk ?
- how you run the example ?

Because I just rebuild the SDK from scratch on branch master, and it works fine for me. I cannot reproduce your problem.

Regards,
Yao
