### ISSUE TITLE
HWCE API

### ISSUE THREAD

**Issue by bpervan** [GreenWaves-Technologies/gap_sdk#246]
Hi,

I'm having trouble utilizing HWCE through its API, which is supposed to be [here](https://github.com/GreenWaves-Technologies/gap_sdk/blob/bbdec24018212447cb9ece8ca615b969994a0a37/rtos/pulp/pulp-os/include/rt/hwce.h) if I'm not mistaken. In the official [documentation](https://greenwaves-technologies.com/manuals/BUILD/HOME/html/index.html) there is not a word about this API, and among examples, I can't find a single one demonstrating a relative simple utilization of the HWCE (i.e. an example simple enough to begin with). Is it actually possible to access HWCE independently through the aforementioned API (or any other similar APIs)?

**Comment by Yaooooo** [comment]
Hi,

Sorry for the confusion, actually, we do have these API, but not really open to be used, since we don't have kernels for using GAP8 HWCE.
The HWCE in GAP8 has too many constraintes, like data alignement, stride number should be 1, cannot support padding, etc.
Therefore, after evaluating with some NN, we concluded that for most kinds of CNN, using HWCE cannot bring much value on power effeciency. Therefore, we stop the support of it in our tools.

In our next generation (GAP9), we will have a much better, powerful HW block for NN.
