### ISSUE TITLE
Frequency and voltage values

### ISSUE THREAD

**Issue by fernandoFernandeSantos** [GreenWaves-Technologies/gap_sdk#364]
Hello

Are there limits for the frequency values where the GAP8 would not work correctly?
I have tried the following frequency and voltage combination on the [CNN benchmarks](https://github.com/GreenWaves-Technologies/gap_sdk/tree/master/benchmarks/gap8/cnn), and it seems to work fine (the output arrays have the same values).

``` C
PMU_set_voltage(1200, 0);
rt_freq_set(RT_FREQ_DOMAIN_FC, 175 * 1000000);
rt_freq_set(RT_FREQ_DOMAIN_CL, 250 * 1000000);
```

I saw another question about [overclocking](https://github.com/GreenWaves-Technologies/gap_sdk/issues/142). However, I would also be interested if there is a range of frequency and voltage values that can be set inside the limits given by the [GAP8 manual](https://gwt-website-files.s3.amazonaws.com/gap8_datasheet.pdf).

Thanks

**Comment by Yaooooo** [comment]
Hi
This is the max voltage and frequency that GAP8 can have. 
So GAP8 can scaling: 
- voltage: 1.0V -1.2V
- Max Frequency: 
    - FC: 150 MHz @ 1.0V; 250MHz @ 1.2V
    - Cluster: 87 MHz @ 1.0V; 170MHz @ 1.2V
 
The answer in overclocking ticked is wrong in fact, since the hyperbus has a HW divider of 2, due to the DDR support, the max frequency of Hyperbus in GAP8 is 250/2 = 125MHz = 250MB/s. 

Hope this helps and sorry for late reply.
