### ISSUE TITLE
Water Meter success check issue

### ISSUE THREAD

**Issue by ronanbyrne96** [GreenWaves-Technologies/gap_sdk#96]
Small fix needed in applications/WaterMeter/Mnist.c:350
```
for(int num=0;num<7;num++){
```
should be
```
for(int num=0;num<=7;num++){
```
So it checks that the last digit is correct.

**Comment by Pafrak** [comment]
Dear ronanbyrne96,
 this is a good point. In this example the training of the NN has been done only with images taken with numbers that are in front position. Thus in the training dataset we do not have numbers that are half visible (i.e. images of a half 4 because the counter is turning to a 5), this is why we skip the least significant number while checking results with the GT. 

I'm adding a comment to explain this in the code.

Thanks
